// <auto-generated />
using System;
using Infrastructure.Database.SqlDataBases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20231216161637_addedusers")]
    partial class addedusers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Animalmodels.Dog", b =>
                {
                    b.Property<Guid>("animalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("animalID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            animalID = new Guid("1ac66071-7f30-4c27-8f80-2874869d12e4"),
                            Name = "Kenta"
                        },
                        new
                        {
                            animalID = new Guid("b3e7bd9d-bf20-49b9-97c8-9be145a47d79"),
                            Name = "Knugen"
                        },
                        new
                        {
                            animalID = new Guid("414d5f8c-fe00-45b0-a495-306aa5b9f7d5"),
                            Name = "Sjöberg"
                        },
                        new
                        {
                            animalID = new Guid("771a02ee-ab37-48be-8d6e-d2bb4df6350e"),
                            Name = "Berra"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345671"),
                            Name = "DogTest1"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345672"),
                            Name = "DogTest2"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345673"),
                            Name = "DogTest3"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Name = "DogTest4"
                        });
                });

            modelBuilder.Entity("Domain.Models.UserModels.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a113ecf-b3e6-48da-80ac-63a047697e81"),
                            Password = "$2a$11$B.6a6n6b24C5N1SS7MSy.uMtdpIqhty8DgBZjqUiBTTLe8oCHFbuC",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("3d626a10-5e3c-46b4-8aef-aa4dc5a26adb"),
                            Password = "$2a$11$PA.0zfRDvtvPGG0uBO6NEem7dc7xWkNcpKMbW0xPEpkEmhpsHiPSi",
                            Role = "Normal",
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
