// <auto-generated />
using System;
using Infrastructure.Database.SqlDataBases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20231219201954_Lagttillkatter")]
    partial class Lagttillkatter
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Animalmodels.Cat", b =>
                {
                    b.Property<Guid>("animalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("LikesToPlay")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("animalID");

                    b.ToTable("Cats");

                    b.HasData(
                        new
                        {
                            animalID = new Guid("74f28898-2461-4da1-898f-b329433eb737"),
                            LikesToPlay = false,
                            Name = "Fluffig"
                        },
                        new
                        {
                            animalID = new Guid("b1e285e7-2432-4ee7-8b4b-33247a8cb9f1"),
                            LikesToPlay = false,
                            Name = "Argjävel"
                        },
                        new
                        {
                            animalID = new Guid("fca3371f-b7da-4158-a071-4c2ba7cbc62e"),
                            LikesToPlay = false,
                            Name = "Simba"
                        },
                        new
                        {
                            animalID = new Guid("737309b9-6bc7-4410-a236-2eef0e4cb0cb"),
                            LikesToPlay = false,
                            Name = "LedsenKatt"
                        });
                });

            modelBuilder.Entity("Domain.Models.Animalmodels.Dog", b =>
                {
                    b.Property<Guid>("animalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("animalID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            animalID = new Guid("1a1af0e1-606d-4108-9459-55d27d1dc5de"),
                            Name = "Kenta"
                        },
                        new
                        {
                            animalID = new Guid("c4abeb61-102e-4c10-8823-89b2b49a1939"),
                            Name = "Knugen"
                        },
                        new
                        {
                            animalID = new Guid("58213449-2379-4f48-b8e4-208e605e1591"),
                            Name = "Sjöberg"
                        },
                        new
                        {
                            animalID = new Guid("f3b16b92-d629-478c-87e6-21c4ff920dfa"),
                            Name = "Berra"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345671"),
                            Name = "DogTest1"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345672"),
                            Name = "DogTest2"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345673"),
                            Name = "DogTest3"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Name = "DogTest4"
                        });
                });

            modelBuilder.Entity("Domain.Models.UserModels.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86b61042-9569-43e5-8524-0a64e504e83b"),
                            Password = "$2a$11$2BT66s/l4Z4LJGjmGOzky.7th2QbSumP3H5YT4ylzJqipMZDfuEIS",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("8488cd98-79ff-472d-a81d-c450bc0d93bd"),
                            Password = "$2a$11$nnCH3mln7nstoJuzg4OGAu0tTUVSAX7U8jbQZeiRlATIm1jh.Jopu",
                            Role = "Normal",
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
