// <auto-generated />
using System;
using Infrastructure.Database.SqlDataBases;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(RealDatabase))]
    [Migration("20231218133333_Clean_Api_DemoDB")]
    partial class Clean_Api_DemoDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Animalmodels.Dog", b =>
                {
                    b.Property<Guid>("animalID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("animalID");

                    b.ToTable("Dogs");

                    b.HasData(
                        new
                        {
                            animalID = new Guid("b896c2e8-bba2-4984-a693-bfea9bf9611c"),
                            Name = "Kenta"
                        },
                        new
                        {
                            animalID = new Guid("fe149300-5fed-4d0e-8772-73bd1175d0fb"),
                            Name = "Knugen"
                        },
                        new
                        {
                            animalID = new Guid("2cf59e0f-94e0-44b6-84c5-f3d98c45f1c2"),
                            Name = "Sjöberg"
                        },
                        new
                        {
                            animalID = new Guid("2d12a821-096f-4ead-913e-30f6d1d85761"),
                            Name = "Berra"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345671"),
                            Name = "DogTest1"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345672"),
                            Name = "DogTest2"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345673"),
                            Name = "DogTest3"
                        },
                        new
                        {
                            animalID = new Guid("12345678-1234-5678-1234-567812345674"),
                            Name = "DogTest4"
                        });
                });

            modelBuilder.Entity("Domain.Models.UserModels.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6e81fdc5-a601-4fe3-afa6-36ee973ea0ed"),
                            Password = "$2a$11$Qmak8YI/vaOaCglddn4Nbu5GYaEE/60Kw8nD5F5/pr6MotnBaJNDG",
                            Role = "Admin",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = new Guid("79ef209d-4e4b-40f8-9108-6c9d64dd41a0"),
                            Password = "$2a$11$0lp.mpcEimZe0wV2.fLUUeFjs6ynlOjyUxJhVPcxzUj04ulhxUhBu",
                            Role = "Normal",
                            UserName = "user"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
